dist: trusty
language: c
script: make
matrix:
  include:
  - compiler: gcc
    env:
    - CFLAGS="-std=c89 -Wall -Wextra -Wshadow -Wpedantic -Werror"

  - compiler: clang
    env:
    - CFLAGS="-std=c89 -Wall -Wextra -Wshadow -Wpedantic -Werror"

  - compiler: sdcc
    env:
    - CFLAGS="-mmcs51 --std-c89 -Werror"
    - PLATFORM_SOURCES=mcs51_putchar.c
    - OBJ_EXT=.rel
    - BIN_EXT=.hex
    - RUN=cat

  - compiler: avr-gcc
    env:
    - CFLAGS="-mmcu=attiny13 -std=c89 -Wall -Wextra -Wshadow -Wpedantic -Werror"
    - COMPILER_PACKAGES="gcc-avr avr-libc"
    - BIN_EXT=.elf
    - RUN=file

  - compiler: avr-gcc
    env:
    - CFLAGS="-mmcu=attiny2313 -std=c89 -Wall -Wextra -Wshadow -Wpedantic -Werror"
    - COMPILER_PACKAGES="gcc-avr avr-libc"
    - BIN_EXT=.elf
    - RUN=file

  - compiler: avr-gcc
    env:
    - CFLAGS="-mmcu=atmega8 -std=c89 -Wall -Wextra -Wshadow -Wpedantic -Werror"
    - COMPILER_PACKAGES="gcc-avr avr-libc"
    - BIN_EXT=.elf
    - RUN=file

before_install:
 - curl http://literate.zbyedidia.webfactional.com/binaries/literate-linux64.tar.gz | sudo tar -xz -C /usr/local/bin 
 - $CC --version || (sudo apt-get update -qq && sudo apt-get install -qq ${COMPILER_PACKAGES:-$CC})
