language: c
script: make
matrix:
  include:
  - compiler: gcc
  - compiler: clang
  - compiler: sdcc
    env:
    - TARGET_OPTS=-mmcs51
    - PLATFORM_SOURCES=mcs51_putchar.c
    - OBJ_EXT=.rel
    - BIN_EXT=.hex
    - RUN=cat
  - compiler: avr-gcc
    env:
    - TARGET_OPTS=-mmcu=attiny2313a
    - COMPILER_PACKAGES="gcc-avr avr-libc"
    - BIN_EXT=.elf
    - RUN=file

before_install:
 - curl http://literate.zbyedidia.webfactional.com/binaries/literate-linux64.tar.gz | sudo tar -xz -C /usr/local/bin 
 - $CC --version || (sudo apt-get update -qq && sudo apt-get install -qq ${COMPILER_PACKAGES:-$CC})
