language: c
script: make
matrix:
  include:
  - compiler: gcc
  - compiler: clang
  - compiler: sdcc
    env:
    - PLATFORM_SOURCES=mcs51_putchar.c
    - TARGET_OPTS=-m${PLATFORM}
    - OBJ=.rel
    - BIN=.hex
    - RUN=cat
  - compiler: avr-gcc
    env:
    - COMPILER_PACKAGE=gcc-avr
    - TARGET_OPTS=-mmcu=attiny2313a
    - RUN=cat

before_install:
 - curl http://literate.zbyedidia.webfactional.com/binaries/literate-linux64.tar.gz | sudo tar -xz -C /usr/local/bin 
 - $CC --version || (sudo apt-get update -qq && sudo apt-get install -qq ${COMPILER_PACKAGE:-$CC})
