language: c
script: make
matrix:
  include:
  - compiler: gcc
    env:
    - TARGET=
    - RUN=
  - compiler: clang
    env:
    - TARGET=
    - RUN=
  - compiler: sdcc
    env:
    - TARGET=-mmcs51
    - RUN=cat
  - compiler: avr-gcc
    env:
    - TARGET=-mmcu=attiny2313a
    - RUN=cat

before_install:
 - curl http://literate.zbyedidia.webfactional.com/binaries/literate-linux64.tar.gz | sudo tar -xz -C /usr/local/bin 
 - $CC --version || (sudo apt-get update -qq && sudo apt-get install -qq $CC)
